version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(actions)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(docker)"

  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/shared
    schedule:
      interval: daily
